//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoViewer.App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhotoViewer.App.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string AppTheme_Dark {
            get {
                return ResourceManager.GetString("AppTheme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string AppTheme_Light {
            get {
                return ResourceManager.GetString("AppTheme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string AppTheme_System {
            get {
                return ResourceManager.GetString("AppTheme_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed aspect radio.
        /// </summary>
        internal static string AspectRadioMode_Fixed {
            get {
                return ResourceManager.GetString("AspectRadioMode_Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free aspect radio.
        /// </summary>
        internal static string AspectRadioMode_Free {
            get {
                return ResourceManager.GetString("AspectRadioMode_Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orginal aspect radio.
        /// </summary>
        internal static string AspectRadioMode_Orginal {
            get {
                return ResourceManager.GetString("AspectRadioMode_Orginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading {0}.
        /// </summary>
        internal static string BitmapFlipViewItem_LoadingMessage {
            get {
                return ResourceManager.GetString("BitmapFlipViewItem_LoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        internal static string BitmapFlipViewItem_ReloadButton {
            get {
                return ResourceManager.GetString("BitmapFlipViewItem_ReloadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string ComparePage_BackButton {
            get {
                return ResourceManager.GetString("ComparePage_BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ComparePage_DeleteButton {
            get {
                return ResourceManager.GetString("ComparePage_DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link zooming and scrolling.
        /// </summary>
        internal static string ComparePage_LinkViewButton {
            get {
                return ResourceManager.GetString("ComparePage_LinkViewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height:.
        /// </summary>
        internal static string CropImageTool_AspectRadioHeightLabel {
            get {
                return ResourceManager.GetString("CropImageTool_AspectRadioHeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width:.
        /// </summary>
        internal static string CropImageTool_AspectRadioWidthLabel {
            get {
                return ResourceManager.GetString("CropImageTool_AspectRadioWidthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CropImageTool_CancelButtonTooltip {
            get {
                return ResourceManager.GetString("CropImageTool_CancelButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string CropImageTool_OptionsButtonTooltip {
            get {
                return ResourceManager.GetString("CropImageTool_OptionsButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string CropImageTool_SaveButtonTooltip {
            get {
                return ResourceManager.GetString("CropImageTool_SaveButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save copy.
        /// </summary>
        internal static string CropImageTool_SaveCopyMenuItem {
            get {
                return ResourceManager.GetString("CropImageTool_SaveCopyMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the files linked to this file?.
        /// </summary>
        internal static string DeleteLinkedFilesDialog_Message {
            get {
                return ResourceManager.GetString("DeleteLinkedFilesDialog_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string DeleteLinkedFilesDialog_No {
            get {
                return ResourceManager.GetString("DeleteLinkedFilesDialog_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember decision (can be changed in the settings).
        /// </summary>
        internal static string DeleteLinkedFilesDialog_Remember {
            get {
                return ResourceManager.GetString("DeleteLinkedFilesDialog_Remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete linked files.
        /// </summary>
        internal static string DeleteLinkedFilesDialog_Title {
            get {
                return ResourceManager.GetString("DeleteLinkedFilesDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string DeleteLinkedFilesDialog_Yes {
            get {
                return ResourceManager.GetString("DeleteLinkedFilesDialog_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete all RAW files for which no other file with the same name exists?.
        /// </summary>
        internal static string DeleteSingleRawFilesDialog_ConfirmMessage {
            get {
                return ResourceManager.GetString("DeleteSingleRawFilesDialog_ConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string DeleteSingleRawFilesDialog_Continue {
            get {
                return ResourceManager.GetString("DeleteSingleRawFilesDialog_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all RAW files could be deleted. The following errors occurred:.
        /// </summary>
        internal static string DeleteSingleRawFilesDialog_ErrorMessage {
            get {
                return ResourceManager.GetString("DeleteSingleRawFilesDialog_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single RAW files are deleted..
        /// </summary>
        internal static string DeleteSingleRawFilesDialog_InProgressMessage {
            get {
                return ResourceManager.GetString("DeleteSingleRawFilesDialog_InProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All single RAW files were successfully deleted..
        /// </summary>
        internal static string DeleteSingleRawFilesDialog_SuccessMessage {
            get {
                return ResourceManager.GetString("DeleteSingleRawFilesDialog_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete single RAW files.
        /// </summary>
        internal static string DeleteSingleRawFilesDialog_Title {
            get {
                return ResourceManager.GetString("DeleteSingleRawFilesDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete single RAW files.
        /// </summary>
        internal static string DeleteSingleRawFilesUICommand_Label {
            get {
                return ResourceManager.GetString("DeleteSingleRawFilesUICommand_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adobe RGB color space.
        /// </summary>
        internal static string DetailsBar_ColorSpaceAdobeRGB {
            get {
                return ResourceManager.GetString("DetailsBar_ColorSpaceAdobeRGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sRGB color space.
        /// </summary>
        internal static string DetailsBar_ColorSpaceSRGB {
            get {
                return ResourceManager.GetString("DetailsBar_ColorSpaceSRGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown color space.
        /// </summary>
        internal static string DetailsBar_ColorSpaceUnknown {
            get {
                return ResourceManager.GetString("DetailsBar_ColorSpaceUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no information available.
        /// </summary>
        internal static string DetailsBar_NoInformationAvailable {
            get {
                return ResourceManager.GetString("DetailsBar_NoInformationAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness.
        /// </summary>
        internal static string EditImageOverlay_Brightness {
            get {
                return ResourceManager.GetString("EditImageOverlay_Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string EditImageOverlay_Cancel {
            get {
                return ResourceManager.GetString("EditImageOverlay_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrast.
        /// </summary>
        internal static string EditImageOverlay_Contrast {
            get {
                return ResourceManager.GetString("EditImageOverlay_Contrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlights.
        /// </summary>
        internal static string EditImageOverlay_Highlights {
            get {
                return ResourceManager.GetString("EditImageOverlay_Highlights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturation.
        /// </summary>
        internal static string EditImageOverlay_Saturation {
            get {
                return ResourceManager.GetString("EditImageOverlay_Saturation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string EditImageOverlay_Save {
            get {
                return ResourceManager.GetString("EditImageOverlay_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save copy.
        /// </summary>
        internal static string EditImageOverlay_SaveCopy {
            get {
                return ResourceManager.GetString("EditImageOverlay_SaveCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadows.
        /// </summary>
        internal static string EditImageOverlay_Shadows {
            get {
                return ResourceManager.GetString("EditImageOverlay_Shadows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharpen.
        /// </summary>
        internal static string EditImageOverlay_Sharpen {
            get {
                return ResourceManager.GetString("EditImageOverlay_Sharpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        internal static string EditImageOverlay_Temperature {
            get {
                return ResourceManager.GetString("EditImageOverlay_Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit image.
        /// </summary>
        internal static string EditImageOverlay_Title {
            get {
                return ResourceManager.GetString("EditImageOverlay_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude.
        /// </summary>
        internal static string EditLocationDialog_AltitudeLabel {
            get {
                return ResourceManager.GetString("EditLocationDialog_AltitudeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference system.
        /// </summary>
        internal static string EditLocationDialog_AltitudeReferenceSystemLabel {
            get {
                return ResourceManager.GetString("EditLocationDialog_AltitudeReferenceSystemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string EditLocationDialog_Cancel {
            get {
                return ResourceManager.GetString("EditLocationDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code and town.
        /// </summary>
        internal static string EditLocationDialog_CityLabel {
            get {
                return ResourceManager.GetString("EditLocationDialog_CityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy coordinates.
        /// </summary>
        internal static string EditLocationDialog_CopyCoordinatesTooltip {
            get {
                return ResourceManager.GetString("EditLocationDialog_CopyCoordinatesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string EditLocationDialog_CountryLabel {
            get {
                return ResourceManager.GetString("EditLocationDialog_CountryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        internal static string EditLocationDialog_LatitudeLabel {
            get {
                return ResourceManager.GetString("EditLocationDialog_LatitudeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        internal static string EditLocationDialog_LongitudeLabel {
            get {
                return ResourceManager.GetString("EditLocationDialog_LongitudeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region / State.
        /// </summary>
        internal static string EditLocationDialog_RegionLabel {
            get {
                return ResourceManager.GetString("EditLocationDialog_RegionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove location.
        /// </summary>
        internal static string EditLocationDialog_RemoveLocation {
            get {
                return ResourceManager.GetString("EditLocationDialog_RemoveLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string EditLocationDialog_Save {
            get {
                return ResourceManager.GetString("EditLocationDialog_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string EditLocationDialog_SearchPlaceholder {
            get {
                return ResourceManager.GetString("EditLocationDialog_SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street and house number.
        /// </summary>
        internal static string EditLocationDialog_StreetLabel {
            get {
                return ResourceManager.GetString("EditLocationDialog_StreetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string EditLocationDialog_TabDetails {
            get {
                return ResourceManager.GetString("EditLocationDialog_TabDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        internal static string EditLocationDialog_TabMap {
            get {
                return ResourceManager.GetString("EditLocationDialog_TabMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit location.
        /// </summary>
        internal static string EditLocationDialog_Title {
            get {
                return ResourceManager.GetString("EditLocationDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle files.
        /// </summary>
        internal static string FileOpenDialog_AllFiles {
            get {
                return ResourceManager.GetString("FileOpenDialog_AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        internal static string FlipViewPageCommandBar_CompareButton {
            get {
                return ResourceManager.GetString("FlipViewPageCommandBar_CompareButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop.
        /// </summary>
        internal static string FlipViewPageCommandBar_CropButton {
            get {
                return ResourceManager.GetString("FlipViewPageCommandBar_CropButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string FlipViewPageCommandBar_DeleteButton {
            get {
                return ResourceManager.GetString("FlipViewPageCommandBar_DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start diashow.
        /// </summary>
        internal static string FlipViewPageCommandBar_DiashowButton {
            get {
                return ResourceManager.GetString("FlipViewPageCommandBar_DiashowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit image.
        /// </summary>
        internal static string FlipViewPageCommandBar_EditButton {
            get {
                return ResourceManager.GetString("FlipViewPageCommandBar_EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show metadata.
        /// </summary>
        internal static string FlipViewPageCommandBar_MetadataButton {
            get {
                return ResourceManager.GetString("FlipViewPageCommandBar_MetadataButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string FlipViewPageCommandBar_NextButton {
            get {
                return ResourceManager.GetString("FlipViewPageCommandBar_NextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder.
        /// </summary>
        internal static string FlipViewPageCommandBar_OpenFolderButton {
            get {
                return ResourceManager.GetString("FlipViewPageCommandBar_OpenFolderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to overview.
        /// </summary>
        internal static string FlipViewPageCommandBar_OverviewButton {
            get {
                return ResourceManager.GetString("FlipViewPageCommandBar_OverviewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string FlipViewPageCommandBar_PreviousButton {
            get {
                return ResourceManager.GetString("FlipViewPageCommandBar_PreviousButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate by 90° clockwise.
        /// </summary>
        internal static string FlipViewPageCommandBar_RotateButton {
            get {
                return ResourceManager.GetString("FlipViewPageCommandBar_RotateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string FlipViewPageCommandBar_SettingsButton {
            get {
                return ResourceManager.GetString("FlipViewPageCommandBar_SettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string FlipViewPageCommandBar_ToolsButton {
            get {
                return ResourceManager.GetString("FlipViewPageCommandBar_ToolsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Generic_Cancel {
            get {
                return ResourceManager.GetString("Generic_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Generic_Close {
            get {
                return ResourceManager.GetString("Generic_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude reference system.
        /// </summary>
        internal static string ImportGpxTrackDialog_AltitudeReferenceSystem {
            get {
                return ResourceManager.GetString("ImportGpxTrackDialog_AltitudeReferenceSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open documentation.
        /// </summary>
        internal static string ImportGpxTrackDialog_AltitudeReferenceSystemInfoToolTip {
            get {
                return ResourceManager.GetString("ImportGpxTrackDialog_AltitudeReferenceSystemInfoToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse GPX file.
        /// </summary>
        internal static string ImportGpxTrackDialog_BrowseFileButton {
            get {
                return ResourceManager.GetString("ImportGpxTrackDialog_BrowseFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The import of the GPX track was completed with errors. {0} photo(s) were updated. The following errors occurred:.
        /// </summary>
        internal static string ImportGpxTrackDialog_ErrorMessage {
            get {
                return ResourceManager.GetString("ImportGpxTrackDialog_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string ImportGpxTrackDialog_ImportButton {
            get {
                return ResourceManager.GetString("ImportGpxTrackDialog_ImportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information from GPX track is applied to photos..
        /// </summary>
        internal static string ImportGpxTrackDialog_InProgressMessage {
            get {
                return ResourceManager.GetString("ImportGpxTrackDialog_InProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file that contains the GPX track you want to import..
        /// </summary>
        internal static string ImportGpxTrackDialog_StartMessage {
            get {
                return ResourceManager.GetString("ImportGpxTrackDialog_StartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPX track was imported successfully. {0} photo(s) were updated..
        /// </summary>
        internal static string ImportGpxTrackDialog_SuccessMessage {
            get {
                return ResourceManager.GetString("ImportGpxTrackDialog_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply GPX track to all photos.
        /// </summary>
        internal static string ImportGpxTrackUICommand_Label {
            get {
                return ResourceManager.GetString("ImportGpxTrackUICommand_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string ItemWithCount_All {
            get {
                return ResourceManager.GetString("ItemWithCount_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading files.
        /// </summary>
        internal static string LoadingFilesMessage {
            get {
                return ResourceManager.GetString("LoadingFilesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string ManageKeywordsDialog_CloseButton {
            get {
                return ResourceManager.GetString("ManageKeywordsDialog_CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string ManageKeywordsDialog_ExportButton {
            get {
                return ResourceManager.GetString("ManageKeywordsDialog_ExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string ManageKeywordsDialog_ImportButton {
            get {
                return ResourceManager.GetString("ManageKeywordsDialog_ImportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string ManageKeywordsDialog_RemoveButton {
            get {
                return ResourceManager.GetString("ManageKeywordsDialog_RemoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string ManageKeywordsDialog_ResetButton {
            get {
                return ResourceManager.GetString("ManageKeywordsDialog_ResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string ManageKeywordsDialog_SearchBoxPlaceholder {
            get {
                return ResourceManager.GetString("ManageKeywordsDialog_SearchBoxPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Keywords.
        /// </summary>
        internal static string ManageKeywordsDialog_Title {
            get {
                return ResourceManager.GetString("ManageKeywordsDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string ManagePeopleDialog_CloseButton {
            get {
                return ResourceManager.GetString("ManagePeopleDialog_CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string ManagePeopleDialog_ExportButton {
            get {
                return ResourceManager.GetString("ManagePeopleDialog_ExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string ManagePeopleDialog_ImportButton {
            get {
                return ResourceManager.GetString("ManagePeopleDialog_ImportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string ManagePeopleDialog_RemoveButton {
            get {
                return ResourceManager.GetString("ManagePeopleDialog_RemoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string ManagePeopleDialog_ResetButton {
            get {
                return ResourceManager.GetString("ManagePeopleDialog_ResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string ManagePeopleDialog_SearchBoxPlaceholder {
            get {
                return ResourceManager.GetString("ManagePeopleDialog_SearchBoxPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage People.
        /// </summary>
        internal static string ManagePeopleDialog_Title {
            get {
                return ResourceManager.GetString("ManagePeopleDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string MediaFileContextMenu_Copy {
            get {
                return ResourceManager.GetString("MediaFileContextMenu_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy file path.
        /// </summary>
        internal static string MediaFileContextMenu_CopyPath {
            get {
                return ResourceManager.GetString("MediaFileContextMenu_CopyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string MediaFileContextMenu_Delete {
            get {
                return ResourceManager.GetString("MediaFileContextMenu_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in new window.
        /// </summary>
        internal static string MediaFileContextMenu_OpenInNewWindows {
            get {
                return ResourceManager.GetString("MediaFileContextMenu_OpenInNewWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open with ....
        /// </summary>
        internal static string MediaFileContextMenu_OpenWidth {
            get {
                return ResourceManager.GetString("MediaFileContextMenu_OpenWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string MediaFileContextMenu_Print {
            get {
                return ResourceManager.GetString("MediaFileContextMenu_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string MediaFileContextMenu_Properties {
            get {
                return ResourceManager.GetString("MediaFileContextMenu_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string MediaFileContextMenu_Rename {
            get {
                return ResourceManager.GetString("MediaFileContextMenu_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate.
        /// </summary>
        internal static string MediaFileContextMenu_Rotate {
            get {
                return ResourceManager.GetString("MediaFileContextMenu_Rotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as ....
        /// </summary>
        internal static string MediaFileContextMenu_SetAs {
            get {
                return ResourceManager.GetString("MediaFileContextMenu_SetAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop background.
        /// </summary>
        internal static string MediaFileContextMenu_SetAsDesktopBackground {
            get {
                return ResourceManager.GetString("MediaFileContextMenu_SetAsDesktopBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lockscreen.
        /// </summary>
        internal static string MediaFileContextMenu_SetAsLockscreenBackground {
            get {
                return ResourceManager.GetString("MediaFileContextMenu_SetAsLockscreenBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string MediaFileContextMenu_Share {
            get {
                return ResourceManager.GetString("MediaFileContextMenu_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string MediaFlipView_DisableDiashowLoop {
            get {
                return ResourceManager.GetString("MediaFlipView_DisableDiashowLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        internal static string MediaFlipView_EnableDiashowLoop {
            get {
                return ResourceManager.GetString("MediaFlipView_EnableDiashowLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string MediaFlipView_ExitDiashow {
            get {
                return ResourceManager.GetString("MediaFlipView_ExitDiashow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add date taken.
        /// </summary>
        internal static string MetadataPanel_AddDateTakenButton {
            get {
                return ResourceManager.GetString("MetadataPanel_AddDateTakenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add keyword.
        /// </summary>
        internal static string MetadataPanel_AddKeywordPlaceholder {
            get {
                return ResourceManager.GetString("MetadataPanel_AddKeywordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add person.
        /// </summary>
        internal static string MetadataPanel_AddPersonPlaceholder {
            get {
                return ResourceManager.GetString("MetadataPanel_AddPersonPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected file does not support metadata.
        /// </summary>
        internal static string MetadataPanel_AnyFileNotSupported {
            get {
                return ResourceManager.GetString("MetadataPanel_AnyFileNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply to all.
        /// </summary>
        internal static string MetadataPanel_ApplyKeywordToAll {
            get {
                return ResourceManager.GetString("MetadataPanel_ApplyKeywordToAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add author.
        /// </summary>
        internal static string MetadataPanel_AuthorPlaceholder {
            get {
                return ResourceManager.GetString("MetadataPanel_AuthorPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors.
        /// </summary>
        internal static string MetadataPanel_AuthorsHeader {
            get {
                return ResourceManager.GetString("MetadataPanel_AuthorsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string MetadataPanel_CloseButtonToolTip {
            get {
                return ResourceManager.GetString("MetadataPanel_CloseButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy from ....
        /// </summary>
        internal static string MetadataPanel_CopyFormOtherPhotoButton {
            get {
                return ResourceManager.GetString("MetadataPanel_CopyFormOtherPhotoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        internal static string MetadataPanel_CopyrightHeader {
            get {
                return ResourceManager.GetString("MetadataPanel_CopyrightHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add copyright.
        /// </summary>
        internal static string MetadataPanel_CopyrightPlaceholder {
            get {
                return ResourceManager.GetString("MetadataPanel_CopyrightPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Taken.
        /// </summary>
        internal static string MetadataPanel_DateTakenHeader {
            get {
                return ResourceManager.GetString("MetadataPanel_DateTakenHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different Values.
        /// </summary>
        internal static string MetadataPanel_DifferentValuesPlaceholder {
            get {
                return ResourceManager.GetString("MetadataPanel_DifferentValuesPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string MetadataPanel_EditLocationButton {
            get {
                return ResourceManager.GetString("MetadataPanel_EditLocationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from GPX file.
        /// </summary>
        internal static string MetadataPanel_ImportFromGpxFileButton {
            get {
                return ResourceManager.GetString("MetadataPanel_ImportFromGpxFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        internal static string MetadataPanel_KeywordsHeader {
            get {
                return ResourceManager.GetString("MetadataPanel_KeywordsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred.
        /// </summary>
        internal static string MetadataPanel_LoadingError {
            get {
                return ResourceManager.GetString("MetadataPanel_LoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string MetadataPanel_LocationHeader {
            get {
                return ResourceManager.GetString("MetadataPanel_LocationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage suggestions.
        /// </summary>
        internal static string MetadataPanel_ManageKeywordSuggestionsButtonTooltip {
            get {
                return ResourceManager.GetString("MetadataPanel_ManageKeywordSuggestionsButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage suggestions.
        /// </summary>
        internal static string MetadataPanel_ManagePeopleSuggestionsButtonTooltip {
            get {
                return ResourceManager.GetString("MetadataPanel_ManagePeopleSuggestionsButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No date taken.
        /// </summary>
        internal static string MetadataPanel_NoDateTakenPresent {
            get {
                return ResourceManager.GetString("MetadataPanel_NoDateTakenPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select files to show metadata.
        /// </summary>
        internal static string MetadataPanel_NoFilesSelected {
            get {
                return ResourceManager.GetString("MetadataPanel_NoFilesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        internal static string MetadataPanel_PeopleHeader {
            get {
                return ResourceManager.GetString("MetadataPanel_PeopleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch mode.
        /// </summary>
        internal static string MetadataPanel_PeopleTaggingPageButton {
            get {
                return ResourceManager.GetString("MetadataPanel_PeopleTaggingPageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        internal static string MetadataPanel_RatingHeader {
            get {
                return ResourceManager.GetString("MetadataPanel_RatingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove keyword.
        /// </summary>
        internal static string MetadataPanel_RemoveKeyword {
            get {
                return ResourceManager.GetString("MetadataPanel_RemoveKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string MetadataPanel_RemovePeopleTag {
            get {
                return ResourceManager.GetString("MetadataPanel_RemovePeopleTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select only supported files.
        /// </summary>
        internal static string MetadataPanel_SelectOnlySupportedFiles {
            get {
                return ResourceManager.GetString("MetadataPanel_SelectOnlySupportedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift date taken.
        /// </summary>
        internal static string MetadataPanel_ShiftDateTakenButton {
            get {
                return ResourceManager.GetString("MetadataPanel_ShiftDateTakenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show on map.
        /// </summary>
        internal static string MetadataPanel_ShowLocationOnMapButton {
            get {
                return ResourceManager.GetString("MetadataPanel_ShowLocationOnMapButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag on photo.
        /// </summary>
        internal static string MetadataPanel_TagPeopleOnPhoto {
            get {
                return ResourceManager.GetString("MetadataPanel_TagPeopleOnPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata.
        /// </summary>
        internal static string MetadataPanel_Title {
            get {
                return ResourceManager.GetString("MetadataPanel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string MetadataPanel_TitleHeader {
            get {
                return ResourceManager.GetString("MetadataPanel_TitleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add title.
        /// </summary>
        internal static string MetadataPanel_TitlePlaceholder {
            get {
                return ResourceManager.GetString("MetadataPanel_TitlePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to move all RAW files to a subfolder?.
        /// </summary>
        internal static string MoveRawFilesToSubfolderDialog_ConfirmationMessage {
            get {
                return ResourceManager.GetString("MoveRawFilesToSubfolderDialog_ConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string MoveRawFilesToSubfolderDialog_Continue {
            get {
                return ResourceManager.GetString("MoveRawFilesToSubfolderDialog_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all files could be moved. The following errors occurred:.
        /// </summary>
        internal static string MoveRawFilesToSubfolderDialog_ErrorMessage {
            get {
                return ResourceManager.GetString("MoveRawFilesToSubfolderDialog_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving RAW files to subfolder..
        /// </summary>
        internal static string MoveRawFilesToSubfolderDialog_InProgressMessage {
            get {
                return ResourceManager.GetString("MoveRawFilesToSubfolderDialog_InProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All RAW files were successfully moved to a subfolder..
        /// </summary>
        internal static string MoveRawFilesToSubfolderDialog_SuccessMessage {
            get {
                return ResourceManager.GetString("MoveRawFilesToSubfolderDialog_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move RAW files to subfolder..
        /// </summary>
        internal static string MoveRawFilesToSubfolderDialog_Title {
            get {
                return ResourceManager.GetString("MoveRawFilesToSubfolderDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move RAW files to subfolder.
        /// </summary>
        internal static string MoveRawFilesToSubfolderUICommand_Label {
            get {
                return ResourceManager.GetString("MoveRawFilesToSubfolderUICommand_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to show.
        /// </summary>
        internal static string NoItemsMessage {
            get {
                return ResourceManager.GetString("NoItemsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder.
        /// </summary>
        internal static string OpenFolderButton {
            get {
                return ResourceManager.GetString("OpenFolderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This photo is tagged with keywords.
        /// </summary>
        internal static string OverviewItem_KeywordsSymbol_Tooltip {
            get {
                return ResourceManager.GetString("OverviewItem_KeywordsSymbol_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This photo has location information.
        /// </summary>
        internal static string OverviewItem_LocationSymbol_Tooltip {
            get {
                return ResourceManager.GetString("OverviewItem_LocationSymbol_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This photo has people tags.
        /// </summary>
        internal static string OverviewItem_PeopleSymbol_Tooltip {
            get {
                return ResourceManager.GetString("OverviewItem_PeopleSymbol_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} elements, {1} selected.
        /// </summary>
        internal static string OverviewPage_SelectionInfo {
            get {
                return ResourceManager.GetString("OverviewPage_SelectionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large thumbnails.
        /// </summary>
        internal static string OverviewPageCommandBar_LargeThumbs {
            get {
                return ResourceManager.GetString("OverviewPageCommandBar_LargeThumbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium thumbnails.
        /// </summary>
        internal static string OverviewPageCommandBar_MediumThumbs {
            get {
                return ResourceManager.GetString("OverviewPageCommandBar_MediumThumbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small thumbnails.
        /// </summary>
        internal static string OverviewPageCommandBar_SmallThumbs {
            get {
                return ResourceManager.GetString("OverviewPageCommandBar_SmallThumbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string OverviewPageCommandBar_ViewButton {
            get {
                return ResourceManager.GetString("OverviewPageCommandBar_ViewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All people.
        /// </summary>
        internal static string PeopleTaggingPage_AllPeople {
            get {
                return ResourceManager.GetString("PeopleTaggingPage_AllPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string PeopleTaggingPage_Back {
            get {
                return ResourceManager.GetString("PeopleTaggingPage_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently tagged people.
        /// </summary>
        internal static string PeopleTaggingPage_RecentPeople {
            get {
                return ResourceManager.GetString("PeopleTaggingPage_RecentPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string PeopleTaggingPage_SearchPeoplePlaceholder {
            get {
                return ResourceManager.GetString("PeopleTaggingPage_SearchPeoplePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to rename all files sorted by date taken with a sequential number as prefix?.
        /// </summary>
        internal static string PrefixFilesByDateDialog_ConfirmationMessage {
            get {
                return ResourceManager.GetString("PrefixFilesByDateDialog_ConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string PrefixFilesByDateDialog_Continue {
            get {
                return ResourceManager.GetString("PrefixFilesByDateDialog_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all files could be renamed. The following errors occurred:.
        /// </summary>
        internal static string PrefixFilesByDateDialog_ErrorMessage {
            get {
                return ResourceManager.GetString("PrefixFilesByDateDialog_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename all files sorted by date taken with a sequential number as prefix..
        /// </summary>
        internal static string PrefixFilesByDateDialog_InProgressMessage {
            get {
                return ResourceManager.GetString("PrefixFilesByDateDialog_InProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files were successfully renamed..
        /// </summary>
        internal static string PrefixFilesByDateDialog_SuccessMessage {
            get {
                return ResourceManager.GetString("PrefixFilesByDateDialog_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename files based on date taken.
        /// </summary>
        internal static string PrefixFilesByDateDialog_Title {
            get {
                return ResourceManager.GetString("PrefixFilesByDateDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename files based on date taken.
        /// </summary>
        internal static string PrefixFilesByDateUICommand_Label {
            get {
                return ResourceManager.GetString("PrefixFilesByDateUICommand_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse unused space.
        /// </summary>
        internal static string Printing_CollapseUnusedSpaceTitle {
            get {
                return ResourceManager.GetString("Printing_CollapseUnusedSpaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input.
        /// </summary>
        internal static string Printing_CopiesInvalidError {
            get {
                return ResourceManager.GetString("Printing_CopiesInvalidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copies per photo.
        /// </summary>
        internal static string Printing_CopiesTitle {
            get {
                return ResourceManager.GetString("Printing_CopiesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height (cm).
        /// </summary>
        internal static string Printing_CustomHeightTitle {
            get {
                return ResourceManager.GetString("Printing_CustomHeightTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input.
        /// </summary>
        internal static string Printing_CustomSizeInvalidError {
            get {
                return ResourceManager.GetString("Printing_CustomSizeInvalidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width (cm).
        /// </summary>
        internal static string Printing_CustomWidthTitle {
            get {
                return ResourceManager.GetString("Printing_CustomWidthTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        internal static string Printing_GridColumnsTitle {
            get {
                return ResourceManager.GetString("Printing_GridColumnsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows.
        /// </summary>
        internal static string Printing_GridRowsTitle {
            get {
                return ResourceManager.GetString("Printing_GridRowsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input.
        /// </summary>
        internal static string Printing_GridSpecificationInvalidError {
            get {
                return ResourceManager.GetString("Printing_GridSpecificationInvalidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        internal static string Printing_HorizontalAlignmentCenter {
            get {
                return ResourceManager.GetString("Printing_HorizontalAlignmentCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string Printing_HorizontalAlignmentLeft {
            get {
                return ResourceManager.GetString("Printing_HorizontalAlignmentLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string Printing_HorizontalAlignmentRight {
            get {
                return ResourceManager.GetString("Printing_HorizontalAlignmentRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Alignment.
        /// </summary>
        internal static string Printing_HorizontalAlignmentTitle {
            get {
                return ResourceManager.GetString("Printing_HorizontalAlignmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 cm x 15 cm.
        /// </summary>
        internal static string Printing_Layout100x150 {
            get {
                return ResourceManager.GetString("Printing_Layout100x150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13 cm x 18 cm.
        /// </summary>
        internal static string Printing_Layout130x180 {
            get {
                return ResourceManager.GetString("Printing_Layout130x180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5,5 cm x 8,8 cm.
        /// </summary>
        internal static string Printing_Layout55x85 {
            get {
                return ResourceManager.GetString("Printing_Layout55x85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9 cm x 13 cm.
        /// </summary>
        internal static string Printing_Layout90x130 {
            get {
                return ResourceManager.GetString("Printing_Layout90x130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string Printing_LayoutCustom {
            get {
                return ResourceManager.GetString("Printing_LayoutCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Page.
        /// </summary>
        internal static string Printing_LayoutFullPage {
            get {
                return ResourceManager.GetString("Printing_LayoutFullPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid.
        /// </summary>
        internal static string Printing_LayoutGrid {
            get {
                return ResourceManager.GetString("Printing_LayoutGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        internal static string Printing_LayoutTitle {
            get {
                return ResourceManager.GetString("Printing_LayoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image does not fit page.
        /// </summary>
        internal static string Printing_PhotoDoesNotFitError {
            get {
                return ResourceManager.GetString("Printing_PhotoDoesNotFitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ProgressDialog_CancelButton {
            get {
                return ResourceManager.GetString("ProgressDialog_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string ProgressDialog_CloseButton {
            get {
                return ResourceManager.GetString("ProgressDialog_CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        internal static string PropertiesDialog_Camera {
            get {
                return ResourceManager.GetString("PropertiesDialog_Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string PropertiesDialog_Close {
            get {
                return ResourceManager.GetString("PropertiesDialog_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date taken.
        /// </summary>
        internal static string PropertiesDialog_DateTaken {
            get {
                return ResourceManager.GetString("PropertiesDialog_DateTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensions.
        /// </summary>
        internal static string PropertiesDialog_Dimensions {
            get {
                return ResourceManager.GetString("PropertiesDialog_Dimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        internal static string PropertiesDialog_FileName {
            get {
                return ResourceManager.GetString("PropertiesDialog_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path.
        /// </summary>
        internal static string PropertiesDialog_FilePath {
            get {
                return ResourceManager.GetString("PropertiesDialog_FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size.
        /// </summary>
        internal static string PropertiesDialog_FileSize {
            get {
                return ResourceManager.GetString("PropertiesDialog_FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aperture.
        /// </summary>
        internal static string PropertiesDialog_FNumber {
            get {
                return ResourceManager.GetString("PropertiesDialog_FNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focal length.
        /// </summary>
        internal static string PropertiesDialog_FocalLength {
            get {
                return ResourceManager.GetString("PropertiesDialog_FocalLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO.
        /// </summary>
        internal static string PropertiesDialog_ISO {
            get {
                return ResourceManager.GetString("PropertiesDialog_ISO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientation.
        /// </summary>
        internal static string PropertiesDialog_Orientation {
            get {
                return ResourceManager.GetString("PropertiesDialog_Orientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in explorer.
        /// </summary>
        internal static string PropertiesDialog_ShowInExplorer {
            get {
                return ResourceManager.GetString("PropertiesDialog_ShowInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutter speed.
        /// </summary>
        internal static string PropertiesDialog_ShutterSpeed {
            get {
                return ResourceManager.GetString("PropertiesDialog_ShutterSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string PropertiesDialog_Title {
            get {
                return ResourceManager.GetString("PropertiesDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string SettingsPage_AboutSectionTittle {
            get {
                return ResourceManager.GetString("SettingsPage_AboutSectionTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string SettingsPage_AppearanceSectionTittle {
            get {
                return ResourceManager.GetString("SettingsPage_AppearanceSectionTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show detailed information bar on startup.
        /// </summary>
        internal static string SettingsPage_AutoShowDetailsBarToogle {
            get {
                return ResourceManager.GetString("SettingsPage_AutoShowDetailsBarToogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show metadata view on startup.
        /// </summary>
        internal static string SettingsPage_AutoShowMetadataPanelToogle {
            get {
                return ResourceManager.GetString("SettingsPage_AutoShowMetadataPanelToogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string SettingsPage_BackButtonTooltip {
            get {
                return ResourceManager.GetString("SettingsPage_BackButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask.
        /// </summary>
        internal static string SettingsPage_DeleteLinkedFilesOption_Ask {
            get {
                return ResourceManager.GetString("SettingsPage_DeleteLinkedFilesOption_Ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        internal static string SettingsPage_DeleteLinkedFilesOption_No {
            get {
                return ResourceManager.GetString("SettingsPage_DeleteLinkedFilesOption_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always.
        /// </summary>
        internal static string SettingsPage_DeleteLinkedFilesOption_Yes {
            get {
                return ResourceManager.GetString("SettingsPage_DeleteLinkedFilesOption_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete linked raw files.
        /// </summary>
        internal static string SettingsPage_DeleteLinkedRawFilesHeader {
            get {
                return ResourceManager.GetString("SettingsPage_DeleteLinkedRawFilesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time span in seconds how long photos are displayed in the diashow.
        /// </summary>
        internal static string SettingsPage_DiashowTimeLabel {
            get {
                return ResourceManager.GetString("SettingsPage_DiashowTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string SettingsPage_ExportSettingsButton {
            get {
                return ResourceManager.GetString("SettingsPage_ExportSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string SettingsPage_ImportSettingsButton {
            get {
                return ResourceManager.GetString("SettingsPage_ImportSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable debug log (requires restart).
        /// </summary>
        internal static string SettingsPage_IsDebugLogEnabledToggleHeader {
            get {
                return ResourceManager.GetString("SettingsPage_IsDebugLogEnabledToggleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal and raw image files are shown as one file.
        /// </summary>
        internal static string SettingsPage_LinkRawFilesDescripiton {
            get {
                return ResourceManager.GetString("SettingsPage_LinkRawFilesDescripiton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link raw files.
        /// </summary>
        internal static string SettingsPage_LinkRawFilesHeader {
            get {
                return ResourceManager.GetString("SettingsPage_LinkRawFilesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        internal static string SettingsPage_LoggingSectionTittle {
            get {
                return ResourceManager.GetString("SettingsPage_LoggingSectionTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage settings.
        /// </summary>
        internal static string SettingsPage_ManageSettingsSectionTittle {
            get {
                return ResourceManager.GetString("SettingsPage_ManageSettingsSectionTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open log file.
        /// </summary>
        internal static string SettingsPage_OpenLogFileButton {
            get {
                return ResourceManager.GetString("SettingsPage_OpenLogFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the name of a subfolder to search for raw files.
        /// </summary>
        internal static string SettingsPage_RawFilesFolderNameDescription {
            get {
                return ResourceManager.GetString("SettingsPage_RawFilesFolderNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder name for raw files.
        /// </summary>
        internal static string SettingsPage_RawFilesFolderNameHeader {
            get {
                return ResourceManager.GetString("SettingsPage_RawFilesFolderNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw files.
        /// </summary>
        internal static string SettingsPage_RawFilesSectionTittle {
            get {
                return ResourceManager.GetString("SettingsPage_RawFilesSectionTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all settings.
        /// </summary>
        internal static string SettingsPage_ResetSettingsButton {
            get {
                return ResourceManager.GetString("SettingsPage_ResetSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show delete animation.
        /// </summary>
        internal static string SettingsPage_ShowDeleteAnimationToggle {
            get {
                return ResourceManager.GetString("SettingsPage_ShowDeleteAnimationToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show video files.
        /// </summary>
        internal static string SettingsPage_ShowVideoFilesHeader {
            get {
                return ResourceManager.GetString("SettingsPage_ShowVideoFilesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string SettingsPage_ThemeHeader {
            get {
                return ResourceManager.GetString("SettingsPage_ThemeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsPage_Title {
            get {
                return ResourceManager.GetString("SettingsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        internal static string SettingsPage_VideoFilesSectionTittle {
            get {
                return ResourceManager.GetString("SettingsPage_VideoFilesSectionTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift date taken of all photos.
        /// </summary>
        internal static string ShiftDatenTakenUICommand_Label {
            get {
                return ResourceManager.GetString("ShiftDatenTakenUICommand_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string ShiftDateTakenDialog_Continue {
            get {
                return ResourceManager.GetString("ShiftDateTakenDialog_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The shifting of the dates taken has been completed. The following errors occurred:.
        /// </summary>
        internal static string ShiftDateTakenDialog_ErrorMessage {
            get {
                return ResourceManager.GetString("ShiftDateTakenDialog_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All dates taken have been successfully shifted.
        /// </summary>
        internal static string ShiftDateTakenDialog_SuccessMessage {
            get {
                return ResourceManager.GetString("ShiftDateTakenDialog_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift dates taken.
        /// </summary>
        internal static string ShiftDateTakenDialog_Title {
            get {
                return ResourceManager.GetString("ShiftDateTakenDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        internal static string SortMenu_Ascending {
            get {
                return ResourceManager.GetString("SortMenu_Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        internal static string SortMenu_Descending {
            get {
                return ResourceManager.GetString("SortMenu_Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        internal static string SortMenu_Sort {
            get {
                return ResourceManager.GetString("SortMenu_Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date taken.
        /// </summary>
        internal static string SortMenu_SortByDateTaken {
            get {
                return ResourceManager.GetString("SortMenu_SortByDateTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        internal static string SortMenu_SortByFileName {
            get {
                return ResourceManager.GetString("SortMenu_SortByFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size.
        /// </summary>
        internal static string SortMenu_SortByFileSize {
            get {
                return ResourceManager.GetString("SortMenu_SortByFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget suggestion.
        /// </summary>
        internal static string TagPeopleTool_ForgetSuggestion {
            get {
                return ResourceManager.GetString("TagPeopleTool_ForgetSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name.
        /// </summary>
        internal static string TagPeopleTool_NamePlaceholder {
            get {
                return ResourceManager.GetString("TagPeopleTool_NamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string TagPeopleTool_RemovePeopleTagMenuItem {
            get {
                return ResourceManager.GetString("TagPeopleTool_RemovePeopleTagMenuItem", resourceCulture);
            }
        }
    }
}
